<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PMenuTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('p_menu')->updateOrInsert([
            'id' => '345',
            'parent_id' => NULL,
            'title' => "Admin Dashboard",
            'icon' => "fas fa-tachometer-alt",
            'route' => "admin.dashboard",
            'sequence' => '2',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2022-09-01 18:25:56",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '346',
            'parent_id' => NULL,
            'title' => "User",
            'icon' => "fas fa-users",
            'route' => "admin.anggota",
            'sequence' => '27',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-09-27 17:15:29",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '347',
            'parent_id' => NULL,
            'title' => "Data Tambahan Profil",
            'icon' => "fas fa-user",
            'route' => null,
            'sequence' => '28',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '348',
            'parent_id' => 347,
            'title' => "Jenis Pendidikan",
            'icon' => null,
            'route' => "admin.profile.pendidikan_jenis",
            'sequence' => '29',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '349',
            'parent_id' => 347,
            'title' => "Jenis Kontak",
            'icon' => null,
            'route' => "admin.profile.kontak_tipe",
            'sequence' => '30',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '350',
            'parent_id' => NULL,
            'title' => "Struktur Organisasi",
            'icon' => "fas fa-sitemap",
            'route' => "admin.kepengurusan.periode",
            'sequence' => '26',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-10-19 22:04:18",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '351',
            'parent_id' => NULL,
            'title' => "Berita",
            'icon' => "fas fa-file-alt",
            'route' => null,
            'sequence' => '10',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-09-27 17:13:56",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '352',
            'parent_id' => 351,
            'title' => "Daftar Artikel",
            'icon' => null,
            'route' => "admin.artikel.data",
            'sequence' => '11',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '353',
            'parent_id' => 351,
            'title' => "Artikel Kategori",
            'icon' => null,
            'route' => "admin.artikel.kategori",
            'sequence' => '12',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '354',
            'parent_id' => 351,
            'title' => "Artikel Tag",
            'icon' => null,
            'route' => "admin.artikel.tag",
            'sequence' => '13',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '355',
            'parent_id' => NULL,
            'title' => "Data Alamat Profil",
            'icon' => "fas fa-map-marker-alt",
            'route' => null,
            'sequence' => '36',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '356',
            'parent_id' => 355,
            'title' => "Provinsi",
            'icon' => null,
            'route' => "admin.address.province",
            'sequence' => '37',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '357',
            'parent_id' => 355,
            'title' => "Kabupaten\/Kota",
            'icon' => null,
            'route' => "admin.address.regencie",
            'sequence' => '38',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '358',
            'parent_id' => 355,
            'title' => "Kecamatan",
            'icon' => null,
            'route' => "admin.address.district",
            'sequence' => '39',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '359',
            'parent_id' => 355,
            'title' => "Desa\/Keluarahan",
            'icon' => null,
            'route' => "admin.address.village",
            'sequence' => '40',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '360',
            'parent_id' => NULL,
            'title' => "Galeri",
            'icon' => "fas fa-images",
            'route' => "admin.galeri",
            'sequence' => '19',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '361',
            'parent_id' => NULL,
            'title' => "Menu Management",
            'icon' => "fas fa-stream",
            'route' => null,
            'sequence' => '4',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '362',
            'parent_id' => NULL,
            'title' => "Pendaftaran",
            'icon' => "fas fa-user-edit",
            'route' => null,
            'sequence' => '14',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '363',
            'parent_id' => NULL,
            'title' => "Sosial Media",
            'icon' => "fas fa-share-alt",
            'route' => "admin.social_media",
            'sequence' => '20',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '364',
            'parent_id' => NULL,
            'title' => "Kontak",
            'icon' => "fas fa-phone",
            'route' => null,
            'sequence' => '21',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '365',
            'parent_id' => NULL,
            'title' => "Instagram",
            'icon' => "fas fa-image",
            'route' => "admin.instagram",
            'sequence' => '18',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '366',
            'parent_id' => 347,
            'title' => "Pengaturan Nama Profil",
            'icon' => "fas fa-check",
            'route' => "admin.username_validation",
            'sequence' => '31',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '367',
            'parent_id' => NULL,
            'title' => "Akses Pengguna",
            'icon' => "fas fa-user-check",
            'route' => null,
            'sequence' => '7',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '368',
            'parent_id' => 367,
            'title' => "Perizinan",
            'icon' => null,
            'route' => "admin.user_access.permission",
            'sequence' => '8',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '369',
            'parent_id' => 367,
            'title' => "Sebagai",
            'icon' => null,
            'route' => "admin.user_access.role",
            'sequence' => '9',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '370',
            'parent_id' => NULL,
            'title' => "User",
            'icon' => null,
            'route' => null,
            'sequence' => '53',
            'active' => '0',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-10-19 22:05:10",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '372',
            'parent_id' => NULL,
            'title' => "Profile",
            'icon' => "fas fa-user",
            'route' => "member.profile",
            'sequence' => '3',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-05-12 16:48:40",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '373',
            'parent_id' => NULL,
            'title' => "Ganti Password",
            'icon' => "fas fa-key",
            'route' => "member.password",
            'sequence' => '57',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:50:28",
            'updated_at' => "2024-09-27 11:14:45",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '386',
            'parent_id' => NULL,
            'title' => "Logout",
            'icon' => "fas fa-sign-out-alt",
            'route' => "logout",
            'sequence' => '58',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-05 23:54:09",
            'updated_at' => "2024-09-27 11:14:45",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '387',
            'parent_id' => 362,
            'title' => "List Data",
            'icon' => null,
            'route' => "admin.pendaftaran.sensus.excel",
            'sequence' => '15',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-06 00:05:47",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '388',
            'parent_id' => 362,
            'title' => "Sensus Anggota",
            'icon' => null,
            'route' => "admin.pendaftaran.sensus",
            'sequence' => '16',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-06 00:06:23",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '389',
            'parent_id' => NULL,
            'title' => "Menu kata Motivasi",
            'icon' => null,
            'route' => null,
            'sequence' => '55',
            'active' => '0',
            'type' => '1',
            'created_at' => "2022-08-06 14:06:05",
            'updated_at' => "2024-11-04 19:41:24",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '390',
            'parent_id' => NULL,
            'title' => "Halaman Utama",
            'icon' => "fas fa-tachometer-alt",
            'route' => "member.dashboard",
            'sequence' => '1',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-06 15:16:19",
            'updated_at' => "2023-02-19 20:38:03",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '392',
            'parent_id' => 362,
            'title' => "Google Forms",
            'icon' => null,
            'route' => "admin.pendaftaran.gform",
            'sequence' => '17',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-08 16:14:54",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '393',
            'parent_id' => NULL,
            'title' => "Utility",
            'icon' => "fas fa-tools",
            'route' => null,
            'sequence' => '41',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-08 22:41:26",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '394',
            'parent_id' => 393,
            'title' => "Notifikasi Depan Atas",
            'icon' => null,
            'route' => "admin.utility.notif_depan_atas",
            'sequence' => '43',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-08 22:41:53",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '395',
            'parent_id' => NULL,
            'title' => "Kata-kata (quotes)",
            'icon' => "fas fa-user-edit",
            'route' => "admin.kata_alumni",
            'sequence' => '50',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-09 15:20:36",
            'updated_at' => "2024-09-27 17:19:49",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '396',
            'parent_id' => NULL,
            'title' => "Kata-kata (quotes)",
            'icon' => "fas fa-user-edit",
            'route' => "member.kata_alumni",
            'sequence' => '56',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-09 15:23:52",
            'updated_at' => "2024-09-27 17:20:14",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '397',
            'parent_id' => NULL,
            'title' => "Setting Halaman",
            'icon' => "fas fa-wrench",
            'route' => null,
            'sequence' => '45',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-14 21:10:57",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '398',
            'parent_id' => 397,
            'title' => "Halaman Admin",
            'icon' => null,
            'route' => "admin.setting.admin",
            'sequence' => '46',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-14 21:11:42",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '399',
            'parent_id' => 397,
            'title' => "Halaman Depan",
            'icon' => null,
            'route' => "admin.setting.front",
            'sequence' => '47',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-14 21:52:45",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '400',
            'parent_id' => 397,
            'title' => "Halaman Utama",
            'icon' => null,
            'route' => "admin.setting.home",
            'sequence' => '48',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-16 14:55:41",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '401',
            'parent_id' => 393,
            'title' => "Hari Besar Nasional",
            'icon' => null,
            'route' => "admin.utility.hari_besar_nasional",
            'sequence' => '44',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-17 21:19:05",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '402',
            'parent_id' => 393,
            'title' => "Notifikasi Admin Atas",
            'icon' => null,
            'route' => "admin.utility.notif_admin_atas",
            'sequence' => '42',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-18 16:42:00",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '403',
            'parent_id' => NULL,
            'title' => "Laporan",
            'icon' => "fas fa-book",
            'route' => null,
            'sequence' => '51',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-18 18:54:07",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '404',
            'parent_id' => 403,
            'title' => "Anggota",
            'icon' => null,
            'route' => "admin.lapooran.anggota.excel",
            'sequence' => '52',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-18 18:55:08",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '405',
            'parent_id' => 361,
            'title' => "Admin",
            'icon' => null,
            'route' => "admin.menu.admin",
            'sequence' => '5',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-20 14:12:45",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '406',
            'parent_id' => 361,
            'title' => "Depan",
            'icon' => null,
            'route' => "admin.menu.frontend",
            'sequence' => '6',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-20 14:16:07",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '407',
            'parent_id' => 364,
            'title' => "Pesan Diterima",
            'icon' => null,
            'route' => "admin.kontak.message",
            'sequence' => '22',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-21 08:38:20",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '408',
            'parent_id' => 364,
            'title' => "FAQ",
            'icon' => null,
            'route' => "admin.kontak.faq",
            'sequence' => '24',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-21 08:39:18",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '409',
            'parent_id' => 364,
            'title' => "Daftar Kontak",
            'icon' => null,
            'route' => "admin.kontak.list",
            'sequence' => '23',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-08-21 08:40:08",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '411',
            'parent_id' => NULL,
            'title' => "Peralatan",
            'icon' => null,
            'route' => null,
            'sequence' => '25',
            'active' => '1',
            'type' => '1',
            'created_at' => "2022-09-01 18:22:47",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '412',
            'parent_id' => 397,
            'title' => "Halaman Sejarah",
            'icon' => null,
            'route' => "admin.setting.sejarah",
            'sequence' => '49',
            'active' => '1',
            'type' => '1',
            'created_at' => "2023-02-19 10:02:10",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '413',
            'parent_id' => NULL,
            'title' => "Menu Penilaian",
            'icon' => "fas fa-id-card",
            'route' => null,
            'sequence' => '32',
            'active' => '1',
            'type' => '1',
            'created_at' => "2023-05-09 11:53:00",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '414',
            'parent_id' => 413,
            'title' => "Kriteria",
            'icon' => null,
            'route' => "admin.spk.ahp.kriteria",
            'sequence' => '33',
            'active' => '1',
            'type' => '1',
            'created_at' => "2023-05-09 11:54:34",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '415',
            'parent_id' => 413,
            'title' => "Kelola Nilai",
            'icon' => null,
            'route' => "admin.spk.ahp.alternatif",
            'sequence' => '34',
            'active' => '1',
            'type' => '1',
            'created_at' => "2023-05-09 14:17:57",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '416',
            'parent_id' => 413,
            'title' => "Hasil",
            'icon' => null,
            'route' => "admin.spk.ahp.perhitungan",
            'sequence' => '35',
            'active' => '1',
            'type' => '1',
            'created_at' => "2023-05-09 14:18:10",
            'updated_at' => "2024-05-12 23:14:06",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '417',
            'parent_id' => NULL,
            'title' => "Program Belajar",
            'icon' => "fas fa-share-alt",
            'route' => "admin.home.program_pembelajaran",
            'sequence' => '54',
            'active' => '0',
            'type' => '1',
            'created_at' => "2024-09-27 11:13:30",
            'updated_at' => "2024-11-04 19:41:00",
        ]);
        DB::table('p_menu')->updateOrInsert([
            'id' => '418',
            'parent_id' => NULL,
            'title' => "Testimoni",
            'icon' => null,
            'route' => "admin.home.testimonial",
            'sequence' => '58',
            'active' => '1',
            'type' => '1',
            'created_at' => "2024-09-27 11:16:09",
            'updated_at' => "2024-09-27 11:16:09",
        ]);
    }
}
